project:
  type: website
  output-dir: docs

website:
  title: "Tallex0.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: links.qmd
        text: Links
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



