project:
  type: website
  output-dir: docs

website:
  title: "Tallex0.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: links.qmd
        text: Links
      - href: Resume.html
        text: Resume
      - href: projects.qmd
        text: Projects
resources: Resume.html
reference: /Users/tallex/Downloads/Resume.html
format:
  html:
    theme: minty
    css: styles.css
    toc: true



