---
title: "Blackfoot Fish Data"
author: "Alex Goodman"
format:
  html:
    self-contained: True
    code-tools: True
    code-fold: True
execute:
  echo: true
  error: true
  message: false
  warning: false
theme: cerulean
---

2.1

```{r}
library(tidyverse)
library(here)
library(ggridges)
library(ggplot2)
library(cowplot)
fish <- read_csv(here::here('portfolio_files', 'data', 'BlackfootFish.csv'))

fish |>
  summarize(across(.col = `trip`:`species`, 
         .fns = ~sum(is.na(.x))))

#There are 1796 missing values for fish weight, and that is the only variable with missing values.
  
```

2.2
```{r}
fish_clean <- fish|>
  filter(is.na(weight))|>
  select(trip, weight, year, section)|>
  mutate(trip = if_else(trip == 1, 'Trip 1', 'Trip 2'))

ggplot(data=fish_clean, mapping = aes(
  x = year, fill = section)) +
  geom_bar() +
  facet_wrap(~trip) +
  labs(x = 'Year', y= NULL, title = 'Missing Weights of Blackfoot Fish')



```

3.1/3.2
```{r}
rescale_01 <- function(vec) {
    stopifnot(is.numeric(vec) | length(vec) > 1)
    min_vec = min(vec)
    vecscale = (vec - min_vec) / 
           (max(vec) - min_vec)
    return(vecscale)
}

#Function simple test (3.3)
vec <- 34:46
rescale_01(vec)
```

3.4
```{r}
#| layout-ncol: 2
lnorm <- ggplot(data=fish, mapping = aes(x=length)) +
  geom_histogram() +
  labs(x = NULL, y = NULL, title = 'Blackfoot Fish Length vs. Rescaled Length')

lres <- ggplot(data=fish, mapping = aes(x = rescale_01(length))) +
  geom_histogram() +
  labs(x = 'Length', y = NULL)

plot_grid(lnorm, lres, ncol = 1)
```

3.5/3.6
```{r}
rescale_column <- function(df, var_vec){
  fish <- fish |>
    mutate(across(.cols = {{ var_vec }}, 
                  ~ rescale_01(.x)
                  )
           )
  fish
}

fish <- fish |>
  rescale_column(var_vec = c(length, weight))
print(fish)

```
