---
title: "Kable Work"
author: "Alex Goodman"
format:
  html:
    self-contained: True
    code-tools: True
    code-fold: True
execute:
  echo: true
  error: true
  message: false
  warning: false
theme: cerulean
---

```{r}
library(tidyverse)
library(here)
library(gt)
library(DT)
library(kableExtra)

```

```{r}
namesA <- read_csv(here::here('portfolio_files', 'data', 'StateNames_A.csv'))
datatable(namesA)
```

2.
```{r}
namesAllison <- namesA |>
  filter(`Name` == 'Allison') |>
  rename(sex = Gender) |>
  select(Name, sex, State, Count) |>
  group_by(`State`, sex) |>
  summarize(total_names = sum(Count)) |>
  pivot_wider(names_from = sex, values_from = total_names, values_fill = 0)
namesAllisonF <- namesAllison |>
  select(`State`, `F`)


namesAllison |>
    knitr::kable(format = "html", 
               digits = 3, 
               col.names = 
                 c("State", 
                   "F", 
                   "M"),
               caption = "Number of Allisons in the U.S by State and Sex")

```
3.
```{r}
names_viz <- namesA |>
  filter(`Name` == 'Allison') |>
  rename(sex = Gender)

my_viz <- names_viz |>
  group_by(`Year`) |>
  summarize(total_names = sum(Count))

ggplot(data = my_viz, mapping = aes(x = `Year`, y = total_names)) +
  geom_line() +
  geom_point() +
  labs(y = NULL, title = "Popularity of the name 'Allison' in the U.S. by Count")
  
  

```
4.
```{r}
allison_lm <- my_viz |>
  lm(total_names ~ Year, data = _) 
  
broom::tidy(allison_lm)

```
5.
```{r}
#Regression Equation
# y = 209815.052 - 101.581x

allison_lm |> 
  broom::augment() |> 
  ggplot(mapping = aes(y = .resid, x = .fitted)) +
  geom_point() +
  geom_line()

# The pattern of residuals appears to have a relatively u-shaped form in the middle, with a couple of smaller curves on the edges. It is pretty hard to tell whether the residuals are scattered randomly or have a nonlinear pattern, so it could really go either way. Because there tends to be a larger u-shape in the middle of the distribution, I would say a quadratic model or another nonlinear model could fit the data better than a linear one. So there seems to be a decline in the name 'Allison' and unfortunately, according to the format of the question and the model, the name isn't as 'cool' anymore.

  
```
5.


```{r}

allans <- namesA |>
  filter(`Gender` == 'M', `Name` %in% c('Allan', 'Alan', 'Allen')) |>
  rename(sex = Gender)

my_viz2 <- allans |>
  group_by(`Year`) |>
  summarize(total_names = sum(Count))

ggplot(data = my_viz2, mapping = aes(x = `Year`, y = total_names)) +
  geom_line() +
  geom_point() +
  labs(y = NULL, title = "Popularity of the names 'Allan', 'Alan', and 'Allen' in the U.S. by Count")
  

```

```{r}
# 9

allans2 <- namesA |>
  rename(sex = Gender) |>
  filter(Year == 2000, Name == 'Allan' | Name == 'Alan' | Name == 'Allen', State == 'PA' | State == 'CA' ) |>
  select(Name, sex, State, Count) |>
  group_by(`Name`, `State`) |>
  summarize(total_names = sum(Count)) |>
  group_by(`State`) |>
  mutate(total_names = total_names / sum(total_names)) |>
  pivot_wider(names_from = Name, values_from = total_names, values_fill = 0)


allans2 %>%
    knitr::kable(format = "html", 
               digits = 3, 
               col.names = 
                 c("State", 
                   "Alan", 
                   "Allan",
                   "Allen"),
               caption = "Proportion of Allans, Allens, and Alans in CA and PA") %>%
  kableExtra::kable_styling(font_size = 20) %>%
  kableExtra::kable_classic(html_font = "verdana")
```
percentage breakdown: from CA: 66% Alan, 15% Allan, 20% Allen. from PA: 43% Alan, 10% Allan, 47% Allen. 

Challenge 9

Part 1 - completed above
Part 2 - I used the font size option for the last table from the kableExtra package. I also changed the font to verdana with the kable_classic() theming option, and added a title. 
Part 3 - added at beginning

