project:
  type: website
  output-dir: docs

website:
  title: "Alex Goodman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: links.qmd
        text: Links
      - href: ResumePic2.png
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
format:
  html:
    theme: minty
    css: styles.css
    toc: true



